name: Update Submodule on Dispatch

on:
  repository_dispatch:
    types: [update-submodule]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update Submodule
        run: |
          cd public/blog
          git fetch origin
          git reset --hard origin/main
          cd ../..
          git add public/blog
          git commit -m "Updated submodule to latest commit" || echo "No changes to commit"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/winzamark123/portfolio-website.git main
